authentications/urls.py
from django.contrib import admin
from django.contrib import auth
from django.urls import path
from . import views

app_name = "authentications"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('volunteerRegister/', views.volunteerRegister, name='volunteerRegister'),
    path('superviorRegister/', views.superviorRegister, name='superviorRegister'),
    path('adminRegister/', views.adminRegister, name='adminRegister'),
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('index/', views.index, name='index'),

]

srrr/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

authentications/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils import timezone


class UsersManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, name,gender,type, password, **extra_fields):

        email = self.normalize_email(email)
        user = self.model(
            email=email,
            name=name,
            gender=gender,
            type=type,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, name,gender,type, password, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, name,gender,type, password, **extra_fields)

    def create_superuser(self, email, name,gender, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, name,gender,1, password, **extra_fields)


class Users(AbstractBaseUser, PermissionsMixin):
    genderchoices = (('male', 'male'), ('female', 'female'))
    usertypes = ((1, "admin"), (2, "supervisor"), (3, "volunteer"))

    email = models.EmailField(unique=True)
    name = models.CharField(max_length=150)
    gender = models.CharField(choices=genderchoices, max_length=6)
    type = models.IntegerField(choices=usertypes, default=3)
    password = models.CharField(max_length=15)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    objects = UsersManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name', 'gender','password']


class supervisor(models.Model):
    user= models.ForeignKey(Users,on_delete=models.CASCADE)
    national_number = models.CharField(max_length=15, unique=True)

    def __str__(self):
        return self.user.email

authentications/forms.py
from django import forms
from .models import Users
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class AccountCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = Users
        fields = ('email', 'name', 'gender')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("you should Enter the same password above")
        return password2

    def save(self, commit=True):

        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user




class SupervisorCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = Users
        fields = ('email', 'name', 'gender')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("you should Enter the same password above")
        return password2

    def save(self, commit=True):

        user = super().save(commit=False)
        user.type=2
        user.is_staff=True
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user



class AdminCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = Users
        fields = ('email', 'name', 'gender')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("you should Enter the same password above")
        return password2

    def save(self, commit=True):

        user = super().save(commit=False)
        user.type = 1
        user.is_staff = True
        user.is_superuser=True
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

authentications/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.shortcuts import render
from django.contrib import auth

from django.http import Http404
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from .forms import  AccountCreationForm, SupervisorCreationForm ,AdminCreationForm
from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from django.template import Context


#################### index#######################################
def index(request):
    return render(request, 'user/index.html', {'title' :'index'})

########### register here #####################################
def volunteerRegister(request):
    if request.method == 'POST':
        form = AccountCreationForm(request.POST)
        if form.is_valid():
            form.save()
            email = request.POST.get('email')
            password = request.POST.get('password')
            print(email, password)
            user = auth.authenticate(username=email, password=password)

            if user:
                if user.is_active:
                    auth.login(request, user)
                    return HttpResponseRedirect(reverse('authentications:index'))
                return HttpResponse('Your id is inactive')
            return HttpResponse('Invalid login details provided')


    else:
        form =AccountCreationForm()
    return render(request, 'user/register.html', {'form': form, 'title' :'reqister here'})

def superviorRegister(request):
    if request.method == 'POST':
        form = SupervisorCreationForm(request.POST)
        if form.is_valid():
            form.save()
            email = request.POST.get('email')
            password = request.POST.get('password')
            print(email, password)
            user = auth.authenticate(username=email, password=password)

            if user:
                if user.is_active:
                    auth.login(request, user)
                    return HttpResponseRedirect(reverse('authentications:index'))
                return HttpResponse('Your id is inactive')
            return HttpResponse('Invalid login details provided')


    else:
        form =SupervisorCreationForm()
    return render(request, 'user/register2.html', {'form': form, 'title' :'reqister here'})

def adminRegister(request):
    if request.method == 'POST':
        form = AdminCreationForm(request.POST)
        if form.is_valid():
            form.save()
            email = request.POST.get('email')
            password = request.POST.get('password1')
            print(email, password)
            user = auth.authenticate(username=email, password=password)

            if user:
                if user.is_active:
                    auth.login(request, user)
                    return HttpResponseRedirect(reverse('authentications:index'))
                return HttpResponse('Your id is inactive')
            return HttpResponse('Invalid login details provided')


    else:
        form =AdminCreationForm()
    return render(request, 'user/register1.html', {'form': form, 'title' :'reqister here'})

################ login forms###################################################

def login(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        print(email,password)
        user = auth.authenticate(username=email, password=password)

        if user:
            if user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('authentications:index'))
            return HttpResponse('Your id is inactive')
        return HttpResponse('Invalid login details provided')


    context = {}
    return render(request, 'user/login.html', context=context)



def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('authentications:index'))

authentications/templates/user/Email.html
1 <!DOCTYPE html>
2 <html lang="en" dir="ltr">
3 	<head>
4 		<meta charset="utf-8">
5 		<title></title>
6 		<style>
7 			@import url('https://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900');
8 		</style>
9 	</head>
10 	<body style="background: #f5f8fa;font-family: 'Roboto', sans-serif;">
11 		<div style="width: 90%;max-width:600px;margin: 20px auto;background: #ffffff;">
12 			<section style="margin: 0 15px;color:#425b76;">
13 				<h2 style="margin: 40px 0 27px 0;text-align: center;">Thank you to registration</h2>
14 				<hr style="border:0;border-top: 1px solid rgba(66,91,118,0.3);max-width: 50%">
15 				<p style="font-size:15.5px;font-weight: bold;margin:40px 20px 15px 20px;">Hi {{username}}, we have received your details and will process soon.</p>
16 			</section>
17 		</div>
18 	</body>
19 </html>

authentications/templates/user/index.html
<!DOCTYPE html>
<html>
	<head lang=en>
		<meta charset="utf-8" />
		<title>
			Monga
			{% block title_block %}
			{% endblock title_block %}
		</title>
	</head>

	<body>
		<div>
			<ul>

				{% if user.is_authenticated %}
					<li> <a href="{% url 'authentications:index'%}"> home </a> </li>
					<li> <a href="{% url 'authentications:logout' %}"> Logout </a> </li>
				{% else %}
					<li> <a href="{% url 'authentications:register' %}"> Sign up </a> </li>
					<li> <a href="{% url 'authentications:log' %}"> Login </a> </li>

				{% endif %}
			</ul>
		</div>
		<hr />

		<!-- body block  -->
		<!-- substitute this block as you need per page -->
		<div>
			{% block body_block %}
			{% endblock body_block %}
		</div>
		<hr />
		<!-- body block ends -->

<a href=""> forget pasword</a>

	</body>
</html>

authentications/templates/user/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  <title>Account-Loved One </title>
  
</head>
<body>

   <div class="container">
      <div class="navbar">

           <nav>
             <ul id="MenuItems">
               <li><a href="{% url 'authentications:index'  %}">Home</a></li>
               <li><a href="{% url 'authentications:index'  %}">Products</a></li>
               <li><a href="{% url 'authentications:index'  %}">Account</a></li>
               <li><a href="">About</a></li>
               <li><a href="{% url 'authentications:index'  %}">Contact</a></li>
            </ul>
          </nav>

       </div>

 </div>
<!------login & register------>
<div class="account-page">
    <div class="container">
        <div class="row">

            <div class="col6">
                <div class="form-container">
                    <div class="form-btn">
                        <span id="login">Login</span>
                          <span>Register</span>

                        <hr id="indicator">
                    </div>
                    <form id="login_form" method="post" action="{% url 'authentications:log' %}">
                        {% csrf_token %}
                         <input type="text" name="email" />
                         <input type="password" name="password"/>
                        <button type="Submit" class="btn">Login</button>

                        <a href=" ">Forget Password</a>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
<div class="footer">
<div class="container">
  <div class="row">
    <div class="footer-col1">
      <h3>Download Our App</h3>
      <p>Download App for Android and iOS Mobile Phone</p>
<div class="app-logo">

</div>
    </div>
    <div class="footer-col2">

       <p> Our Purpose Is To Sustainably Make Our Customers Happy and Satisfied </p>
    </div>
   <div class="footer-col3">
       <h3>Useful Links</h3>
       <ul>
        <li>Coupons</li>
        <li>Return Policy</li>
       </ul>
   </div>
   <div class="footer-col4">
      <h3>Follow us</h3>
       <ul>
          <li>Facebook</li>
          <li>Instagram</li>
          <li>Twitter</li>
       </ul>
   </div>
  </div>
<hr>
<p class="copyright">Copyrights &#169 2021-Designer Afnan</p>
</div>
</div>


</body>
</html>

authentications/templates/user/register.html
<h1> Register </h1>
	<form id="form" method="post" action="{% url 'authentications:register' %}" enctype="multipart/form-data">
		{% csrf_token %}


		{% for field in form%}
			<div>
				{{ field.errors }}
				{{ field.label_tag }} {{ field }}
				<p> {{ field.help_text }} </p>
			</div>
		{% endfor %}


		<input type="submit" name="submit" value="Sign Up">
	</form>

authentications/templates/user/register1.html
<h1> Register </h1>
	<form id="form" method="post" action="{% url 'authentications:register1' %}" enctype="multipart/form-data">
		{% csrf_token %}


		{% for field in form%}
			<div>
				{{ field.errors }}
				{{ field.label_tag }} {{ field }}
				<p> {{ field.help_text }} </p>
			</div>
		{% endfor %}


		<input type="submit" name="submit" value="Sign Up">
	</form>

authentications/templates/user/register2.html
<h1> Register </h1>
	<form id="form" method="post" action="{% url 'authentications:register2' %}" enctype="multipart/form-data">
		{% csrf_token %}


		{% for field in form%}
			<div>
				{{ field.errors }}
				{{ field.label_tag }} {{ field }}
				<p> {{ field.help_text }} </p>
			</div>
		{% endfor %}


		<input type="submit" name="submit" value="Sign Up">
	</form>